# Application
spring.application.name=paytrack-backend
server.port=8080
spring.security.user.name=admin
spring.security.user.password=paytrack123
spring.security.user.roles=ADMIN

# H2 Database (Oracle-compatible SQL syntax)
spring.datasource.url=jdbc:h2:mem:paytrackdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=paytrack-group
spring.kafka.consumer.auto-offset-reset=earliest

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Enable SQL initialization
spring.sql.init.mode=always

# Location of data.sql (default is fine, but explicit is better)
spring.sql.init.data-locations=classpath:data.sql

# Continue even if there are errors
spring.sql.init.continue-on-error=true

spring.jpa.properties.hibernate.format_sql=true